# Generated by Django 4.1.7 on 2023-03-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reserve", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reserve",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pdf",
            name="other",
            field=models.ManyToManyField(to="reserve.other"),
        ),
        migrations.AddField(
            model_name="pdf",
            name="reserve",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdf",
                to="reserve.reserve",
            ),
        ),
    ]
