# Generated by Django 4.1.7 on 2023-03-18 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdf",
            name="number",
        ),
    ]
