# Generated by Django 4.1.7 on 2023-03-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0003_remove_pdf_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="reserve",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pdf",
                to="reserve.reserve",
            ),
        ),
    ]
