# Generated by Django 4.2 on 2023-04-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0004_alter_pdf_reserve"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="avance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="pdf",
            name="cheque_info",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Cheque info"
            ),
        ),
        migrations.AddField(
            model_name="pdf",
            name="payment_type",
            field=models.CharField(
                blank=True,
                choices=[("E", "Espece"), ("C", "Cheque"), ("T", "TPE")],
                max_length=1,
                null=True,
            ),
        ),
    ]
