# Generated by Django 4.2 on 2023-04-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0005_pdf_avance_pdf_cheque_info_pdf_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="avance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
