# Generated by Django 4.2 on 2023-04-05 23:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0006_alter_pdf_avance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="avance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=15
            ),
        ),
    ]
