# Generated by Django 4.2 on 2023-04-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0010_alter_pdf_reserve_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="avance",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
