# Generated by Django 4.2 on 2023-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0012_alter_pdf_avance_alter_pdf_reserve_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="type",
            field=models.CharField(
                choices=[("F", "Facture"), ("D", "Devis"), ("B", "Bon")],
                default="F",
                max_length=1,
            ),
        ),
    ]
