# Generated by Django 4.2 on 2023-04-23 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0014_remove_pdf_client_remove_pdf_reserve_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="other",
            name="created_at",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.now, verbose_name="créé à"
            ),
        ),
        migrations.AlterField(
            model_name="other",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="mis à jour à"),
        ),
        migrations.AlterField(
            model_name="pdf",
            name="created_at",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.now, verbose_name="créé à"
            ),
        ),
        migrations.AlterField(
            model_name="pdf",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="mis à jour à"),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="created_at",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.now, verbose_name="créé à"
            ),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="mis à jour à"),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.now, verbose_name="créé à"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated_at",
            field=models.DateField(auto_now=True, verbose_name="mis à jour à"),
        ),
    ]
