# Generated by Django 4.2 on 2023-04-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0015_alter_other_created_at_alter_other_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="charge",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
    ]
