# Generated by Django 4.2 on 2023-04-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0016_pdf_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdf",
            name="other",
            field=models.ManyToManyField(related_name="others", to="reserve.other"),
        ),
    ]
