# Generated by Django 4.2 on 2023-05-06 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0017_alter_pdf_other"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="other",
            options={"verbose_name": "charge", "verbose_name_plural": "charges"},
        ),
        migrations.RemoveField(
            model_name="pdf",
            name="other",
        ),
        migrations.AddField(
            model_name="reserve",
            name="other",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="others", to="reserve.other"
            ),
        ),
        migrations.CreateModel(
            name="Plate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="créé à",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="mis à jour à"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("number", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("B", "petit déjeuner"),
                            ("L", "déjeuner"),
                            ("D", "dîner"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "reserve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plates",
                        to="reserve.reserve",
                    ),
                ),
            ],
            options={
                "verbose_name": "plat",
                "verbose_name_plural": "plats",
            },
        ),
        migrations.CreateModel(
            name="Intem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="créé à",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="mis à jour à"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("B", "Booking"), ("C", "Client direct")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "reserve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interms",
                        to="reserve.reserve",
                    ),
                ),
            ],
            options={
                "verbose_name": "intermédiaire",
                "verbose_name_plural": "intermédiaires",
            },
        ),
    ]
