# Generated by Django 4.2 on 2023-05-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0018_alter_other_options_remove_pdf_other_reserve_other_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserve",
            name="other",
            field=models.ManyToManyField(
                blank=True, related_name="others", to="reserve.other"
            ),
        ),
    ]
