# Generated by Django 4.2.1 on 2023-05-13 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0019_alter_reserve_other"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdf",
            name="charge",
        ),
    ]
