# Generated by Django 4.2.1 on 2023-05-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0020_remove_pdf_charge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intem",
            name="type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
