# Generated by Django 4.2.1 on 2023-05-13 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0021_alter_intem_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="créé à",
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="mis à jour à"),
                ),
                ("description", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
