# Generated by Django 4.2.1 on 2023-05-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reserve", "0022_bon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intem",
            name="reserve",
        ),
        migrations.AddField(
            model_name="reserve",
            name="interm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interms",
                to="reserve.intem",
            ),
        ),
    ]
